import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "A.S",
  description: "Generated by create next app",
  openGraph: {
    title: "A.S",
    description: "Generated by create next app",
    url: "https://sukhlovesakash.vercel.app/",
    siteName: "A.S",
    type: "website",
    images: [
      {
        url: "https://sukhlovesakash.vercel.app/sukh.png", 
        width: 1200,
        height: 630,
        alt: "A.S Website Preview",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "A.S",
    description: "Generated by create next app",
    images: ["https://sukhlovesakash.vercel.app/sukh.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
